
const REQUEST_API_POKEMON = 'REQUEST_API_POKEMON'

const REQUEST_API_POKEMON_SUCCESS = 'REQUEST_API_SUCCESS'

const REQUEST_API_POKEMON_FAILURE = 'REQUEST_API_FAILURE'


const REQUEST_API_POKEMON_DETAILS = 'REQUEST_API_POKEMON_DETAILS'

const REQUEST_DETAILS_POKEMON_REQUEST = 'REQUEST_DETAILS_POKEMON_REQUEST'
const REQUEST_DETAILS_POKEMON_SUCCESS = 'REQUEST_DETAILS_POKEMON_SUCCESS'
const REQUEST_DETAILS_POKEMON_FAILURE = 'REQUEST_DETAILS_POKEMON_FAILURE'
export {
    REQUEST_API_POKEMON,
    REQUEST_API_POKEMON_SUCCESS,
    REQUEST_API_POKEMON_FAILURE,
    REQUEST_API_POKEMON_DETAILS,

    REQUEST_DETAILS_POKEMON_REQUEST,
    REQUEST_DETAILS_POKEMON_SUCCESS,
    REQUEST_DETAILS_POKEMON_FAILURE
}